services:
  postgres:
    image: postgis/postgis:15-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logisty
    ports:
      - "5432:5432"
      
  tileserver-gl:
    image: maptiler/tileserver-gl
    volumes:
      - .:/data
    ports:
      - 8081:8080
    command: --file poland.mbtiles
