spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/logisty
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true
jwt:
  key: uM3PZy7bj9ge5CD/yeK7gzTxyYPsIa9srrgdyNe2Z18=
  access-token-expiration: 432000000
  refresh-token-expiration: 86400000
