quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/logisty
  hibernate-orm:
    database:
      generation: update