name: Users CI

on:
  push:
    paths:
      - backend/users/**
  pull_request:
    paths:
      - backend/users/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/users
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
