name: Users CI

on:
  push:
    paths:
      - backend/users/**
  pull_request:
    paths:
      - backend/users/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/users
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
